---
- name: set vars
  set_fact:
    docker_image: '{{ role_beets_image }}'
    docker_container: '{{ role_beets_container }}'
    docker_puid: '{{ role_beets_puid }}'
    docker_pgid: '{{ role_beets_pgid }}'
    docker_tz: '{{ role_beets_tz }}'
    docker_dir_config: '{{ role_beets_dir }}/config'
    docker_dir_music: '{{ role_beets_dir }}/music'
    docker_dir_downloads: '{{ role_beets_dir }}/downloads'
    docker_network: '{{ role_beets_network }}'

- name: Create config directory
  ansible.builtin.file:
    path: '{{ docker_dir_config }}'
    state: directory
    owner: '{{ docker_puid }}'
    group: '{{ docker_pgid }}'
    mode: 0755

- name: Create data directory
  ansible.builtin.file:
    path: '{{ docker_dir_data }}'
    state: directory
    owner: '{{ docker_puid }}'
    group: '{{ docker_pgid }}'
    mode: 0755

- name: Ensure image is pulled
  community.docker.docker_image:
    name: "{{ docker_image }}"
    source: pull
    force_source: yes
  register: pulled

- name: Remove container
  community.docker.docker_container:
    name: "{{ docker_container }}"
    state: absent
  when: pulled.changed

- name: Get infos on container
  community.docker.docker_container_info:
    name: "{{ docker_container }}"
  register: result

- name: Create network
  community.docker.docker_network:
    name: "{{ docker_network }}"
    driver_options:
          com.docker.network.bridge.name: "br-{{ docker_network }}"

- name: Create beets container
  community.docker.docker_container:
    image: '{{ docker_image }}'
    volumes:
     - '{{ docker_dir_config }}:/config:Z'
     - '{{ docker_dir_music }}:/music:Z'
     - '{{ docker_dir_downloads }}:/downloads:Z'
    env:
      PUID: '{{ docker_puid }}'
      PGID: '{{ docker_pgid }}'
      TZ: '{{ docker_tz }}'
    name: "{{ docker_container }}"
    networks:
     - name: "{{ docker_network }}"
    restart_policy: unless-stopped
    state: started
  when:
    pulled.changed
    or
    result.exists == false
